package com.example.model;

public enum TipoVetor {
    CRESCENTE_COM_REPETICAO,
    DECRESCENTE_COM_REPETICAO,
    ALEATORIO_COM_REPETICAO,
    CRESCENTE_SEM_REPETICAO,
    DECRESCENTE_SEM_REPETICAO,
    ALEATORIO_SEM_REPETICAO
}